config/routes.rb
Chippy::Application.routes.draw do
 
  get "static_pages/home"

  get "static_pages/team"

  get "static_pages/adventures"

  get "static_pages/gallery"

# the root URL for the site
  root "static_pages#home"


  get "products/available_stock", to: "products#available_stock"
  

  resources :products do

    resource :basket

  end

  resources :orders

  
  match "orders/new/basket_update", to: "baskets#basket_update", via: [:get, :post], as: :basket_update









devise_for :admin_users, ActiveAdmin::Devise.config


  
  ActiveAdmin.routes(self)

  

  

  




end

app/models/product.rb
class Product < ActiveRecord::Base


	has_many :order_products
	has_many :orders, through: :order_products
  has_many :sizes

  before_save :titleize
  before_create :titleize

  validates :description, :presence => true, :on => :create, :on => :update
  validates :name, :uniqueness => true, :presence => true, :on => :create, :on => :update
  validates :price, :presence => true, :on => :create, :on => :update
  validates :color, :presence => true, :on => :create, :on => :update
  # validates :order_id, :presence => true, :on => :create
  validates :image_file_name, :presence => true, :on => :create, :on => :update

	has_attached_file :image, styles: {large: "480x480#", medium: "240x240#", small: "120x120#"}
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  def titleize
    self.name = self.name.titleize
    self.color = self.color.titleize
    self.image_file_name = self.image_file_name.titleize

  end


# this displays the size only if the current stock number is greater than 0.
  def in_stock
    var = self.sizes
    var.delete_if{|item| item.current_stock_number < 1}
  end

# this calculates the total number of each product, regardless of size, that has been sold
  def total_sold_product
    self.order_products.joins(:order).where(orders: {cancel: false}).collect{|item| item[:quantity]}.sum

  end

# this calculates the total value of sold products, regardless of size
  def total_sold_product_value

    self.price * self.order_products.joins(:order).where(orders: {cancel: false}).collect{|item| item[:quantity]}.sum 

  end

  def self.total_basket_price(basket)
    # where(id: basket.to_a.collect{|item| item[:product_id]}).sum(:price)
    prods = where(id: basket.to_a.collect{|item| item[:product_id]}).collect{|product| [:id => product.id, :price => product.price]}

    price_list = []

    prods.each do |prod|
      price_list << Hash[*prod]
    end  

    # price_list = Hash[*price_list]

    grand_sum = 0

    basket.each do |item|

      # puts "basket"

      # puts grand_sum

      sum = 0

      # puts "sum: #{sum}" 
      
      price_list.each do |listing|

        # puts "price_list"

        # puts "sum: #{sum}"

        # puts price_list

        # puts "listing id #{listing[:id]}"
        # puts "basket product id #{item[:product_id]}"

        if item[:product_id] == listing[:id]
          sum = item[:quantity] * listing[:price]

          # puts "sum on matching #{sum}"

          grand_sum += sum
        end
      # puts "grand sum"

      # puts "#{grand_sum} + grand_sum"

      # puts sum
         
      end   

    end

    grand_sum

  end



end

app/controllers/products_controller.rb
class ProductsController < ApplicationController


	def index
		# show all of the products

		@products = Product.all

	end

	def show
		# show an individual product on a new page. 

		@product = Product.find(params[:id])

	end

	def available_stock

		var = Size.find(params[:size])

		@stocks = stock_number(var)

		respond_to do |format|

            format.js
        end  

	end	


	





end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_flashsuccess.html.erb
<%= flash[:success] %>	
		
		

app/views/products/available_stock.js.erb
$("#quantity-select").empty().append("<% @stocks.each do |stock| %> <option value= '<%= stock %>' > <%= stock %> </option> <% end %>");

app/views/products/index.html.erb
<% @products.each do |product| %>

<div>
	<p><%= product.name %></p>
	<p><%= product.description %></p>
	<p><%= product.color %></p>
	<p><%= product.price %></p>
	<p><%= image_tag product.image(:medium) %></p>
	<p><%= link_to "Show", product_path(product) %></p>

</div>

<% end %>

app/views/products/show.html.erb
<div id="flash-success">
		
<%= render "flashsuccess" %>

</div>	

<div>
<%= @product.name %>
<%= @product.price %>
<%= image_tag @product.image(:large) %>


<%= simple_form_for :basket, url: product_basket_path(@product), remote: true do |f| %>

<%= f.input :size, as: :select, collection: @product.in_stock, selected: 1, required: false, input_html: {id: "size-select"} %>

<%= f.input :quantity, as: :select, collection: stock_number(@product.in_stock.first), selected: 1, required: false, input_html: {id: "quantity-select"} %>


<%= f.button :submit, "Add to basket" %>

<% end %>

</div>