config/routes.rb
Chippy::Application.routes.draw do
 
  get "static_pages/home"

  get "static_pages/team"

  get "static_pages/adventures"

  get "static_pages/gallery"

# the root URL for the site
  root "static_pages#home"


  get "products/available_stock", to: "products#available_stock"
  

  resources :products do

    resource :basket

  end

  resources :orders

  
  match "orders/new/basket_update", to: "baskets#basket_update", via: [:get, :post], as: :basket_update









devise_for :admin_users, ActiveAdmin::Devise.config


  
  ActiveAdmin.routes(self)

  

  

  




end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chippy</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	 <header class="full" id="up">

<!--!!!!!!!!!!!!!!!NAVIGATION!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!-->
		 <div class="menu">
			<nav>

        		<%= link_to pluralize(basket_size, "item"), new_order_path, id: "basket-link" %>
		
      			<%= link_to "Team", static_pages_team_path %>
				
				<%= link_to "Adventures", static_pages_adventures_path %>

				<%= link_to "Gallery", static_pages_gallery_path %>
				
				<%= link_to "Shop", products_path %>


			</nav>
		</div> 




<!--!!!!!!!!!!!!!!!!LOGO PICTURE!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!-->

		<!-- <h1 id="top"> -->

			<!-- <%=  link_to image_tag("../chippywwr.png", :border => 0), root_path %> -->
		
		<!-- </h1> -->

	 </header>  
<%= yield %>

</body>
</html>